name: 'Deploy Trigger Slack Integration'
description: 'Post deploy trigger links to provided slack channel'
inputs:
  webhook_url:
    description: 'Slack webhook endpoint'
    required: true
  slack_channel:
    description: 'Slack channel to which message will be sent. Must include prefix `#`'
    required: true
  preprod_environments:
    description: 'Whitespace-separated list of desired dev environments with format cluster:namespace. EG dev-sbs:personbruker'
    required: false
  default_namespace:
    description: 'Assumed namespace when nothing else is specified, to remove redundancy. Only affects presentation'
    required: false
    default: 'personbruker'
  deploy_proxy_url:
    description: 'Path to deploy trigger proxy app'
    required: false
    default: 'http://localhost:8097/dittnav-deploy'
  allow_prod:
    description: 'Enable/disable prod deploy button. Will show on master branch by default.'
    required: false
  commit_sha:
    description: 'Override for commit specified by GITHUB_SHA.'
    required: false
  commit_branch:
    description: 'Override for branch name.'
    required: false
  commit_message:
    description: 'Latest commit message or general context'
    required: false
runs:
  using: docker
  image: Dockerfile
